#!/bin/sh

CC="gcc" # c compiler to use
SRC="./src/flaggen.c" # path to source code
BIN="./bin" # path to build dir
TARGET="$BIN/flaggen" # path to output binary file
FEH="feh" # image preview program to use -default=feh 
FLAGS="./flags" # path to output image folder

if [ ! -d "$FLAGS" ]; then
    mkdir "$FLAGS"
fi

if [ ! -d "$BIN" ]; then
    mkdir "$BIN"
fi

"$CC" "$SRC" -o "$TARGET" && "$TARGET" $1 $2 $3 && "$FEH" "$FLAGS/flag_$1.png"
